# Generated by Django 3.2.10 on 2022-04-26 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ssd',
            name='disk_size',
            field=models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='硬盘尺寸'),
        ),
        migrations.AlterField(
            model_name='ssd',
            name='flash_type',
            field=models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='闪存类型'),
        ),
        migrations.AlterField(
            model_name='ssd',
            name='interface_type',
            field=models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='接口类型'),
        ),
        migrations.AlterField(
            model_name='ssd',
            name='manufacturer',
            field=models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='制造厂方'),
        ),
        migrations.AlterField(
            model_name='ssd',
            name='name',
            field=models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='固态硬盘名称'),
        ),
    ]
