# Generated by Django 3.2.10 on 2022-04-26 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpu',
            name='architecture',
            field=models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='架构'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='code_name',
            field=models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='核心代号'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='compatible_mainboard',
            field=models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='兼容主板'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='manufacturer',
            field=models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='制造厂方'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='memory_types',
            field=models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='支持内存类型'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='name',
            field=models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='CPU名称'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='process_technology',
            field=models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='制程工艺'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='processor_graphics',
            field=models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='处理器显卡'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='series',
            field=models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='系列'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='sockets_supported',
            field=models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='插槽类型'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='use_conditions',
            field=models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='使用类型'),
        ),
    ]
