# Generated by Django 3.2.10 on 2022-04-26 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='applicable_type',
            field=models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='适用类型'),
        ),
        migrations.AlterField(
            model_name='case',
            name='case_bin',
            field=models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='机箱仓位'),
        ),
        migrations.AlterField(
            model_name='case',
            name='case_color',
            field=models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='机箱颜色'),
        ),
        migrations.AlterField(
            model_name='case',
            name='case_fan',
            field=models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='机箱风扇'),
        ),
        migrations.AlterField(
            model_name='case',
            name='case_material',
            field=models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='机箱材质'),
        ),
        migrations.AlterField(
            model_name='case',
            name='case_size',
            field=models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='机箱尺寸'),
        ),
        migrations.AlterField(
            model_name='case',
            name='case_style',
            field=models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='机箱样式'),
        ),
        migrations.AlterField(
            model_name='case',
            name='case_type',
            field=models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='机箱类型'),
        ),
        migrations.AlterField(
            model_name='case',
            name='case_weight',
            field=models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='机箱重量'),
        ),
        migrations.AlterField(
            model_name='case',
            name='compatible_mainboard',
            field=models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='兼容主板'),
        ),
        migrations.AlterField(
            model_name='case',
            name='expansion_slots',
            field=models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='扩展插槽'),
        ),
        migrations.AlterField(
            model_name='case',
            name='front_interface_description',
            field=models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='前置接口描述'),
        ),
        migrations.AlterField(
            model_name='case',
            name='internal_heat_dissipation_description',
            field=models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='内部散热描述'),
        ),
        migrations.AlterField(
            model_name='case',
            name='manufacturer',
            field=models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='制造厂方'),
        ),
        migrations.AlterField(
            model_name='case',
            name='name',
            field=models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='机箱名称'),
        ),
        migrations.AlterField(
            model_name='case',
            name='other_properties',
            field=models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='其它性能'),
        ),
        migrations.AlterField(
            model_name='case',
            name='power_location',
            field=models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='电源位置'),
        ),
    ]
