# Generated by Django 3.2.10 on 2022-04-25 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=128, verbose_name='显卡名称')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='显卡价格')),
                ('manufacturer', models.CharField(default='', max_length=128, verbose_name='制造厂方')),
                ('GPU_type', models.CharField(default='', max_length=64, verbose_name='显卡类型')),
                ('chip_model', models.CharField(default='', max_length=64, verbose_name='芯片型号')),
                ('chip_code', models.CharField(default='', max_length=64, verbose_name='芯片代号')),
                ('manufacturing_process', models.CharField(default='', max_length=64, verbose_name='制造工艺')),
                ('GPU_interface_standard', models.CharField(default='', max_length=128, verbose_name='显卡接口标准')),
                ('output_interface', models.CharField(default='', max_length=128, verbose_name='输出接口')),
                ('multi_screen_display', models.IntegerField(blank=True, null=True, verbose_name='多屏显示')),
                ('video_memory_capacity', models.IntegerField(blank=True, null=True, verbose_name='显存容量')),
                ('video_memory_type', models.CharField(default='', max_length=128, verbose_name='显存类型')),
                ('video_memory_width', models.IntegerField(blank=True, null=True, verbose_name='显存位宽')),
                ('core_frequency', models.IntegerField(blank=True, null=True, verbose_name='核心频率')),
                ('video_memory_frequency', models.IntegerField(blank=True, null=True, verbose_name='显存频率')),
                ('stream_processor_unit', models.IntegerField(blank=True, null=True, verbose_name='流处理器单元')),
                ('DirectX_version', models.CharField(default='', max_length=64, verbose_name='DirectX 版本')),
                ('maximum_resolution', models.CharField(default='', max_length=64, verbose_name='最大分辨率')),
                ('heat_dissipation_description', models.CharField(default='', max_length=128, verbose_name='散热描述')),
                ('power_interface', models.CharField(default='', max_length=128, verbose_name='电源接口')),
                ('board_size', models.CharField(default='', max_length=64, verbose_name='板卡尺寸')),
                ('characteristic_function', models.CharField(default='', max_length=128, verbose_name='特色功能')),
            ],
            options={
                'verbose_name': '显卡信息',
                'verbose_name_plural': '显卡信息',
            },
        ),
    ]
