# Generated by Django 3.2.10 on 2022-04-25 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HDD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=128, verbose_name='机械硬盘名称')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='机械硬盘价格')),
                ('manufacturer', models.CharField(default='', max_length=128, verbose_name='制造厂方')),
                ('transmission_standard', models.CharField(default='', max_length=64, verbose_name='传输标准')),
                ('disk_type', models.CharField(default='', max_length=64, verbose_name='机械硬盘类型')),
                ('capacity', models.IntegerField(blank=True, null=True, verbose_name='机械硬盘容量')),
                ('speed', models.IntegerField(blank=True, null=True, verbose_name='转速')),
                ('cache_capacity', models.IntegerField(blank=True, null=True, verbose_name='缓存容量')),
                ('disk_size', models.CharField(default='', max_length=64, verbose_name='盘体尺寸')),
                ('interface_type', models.CharField(default='', max_length=64, verbose_name='接口类型')),
            ],
            options={
                'verbose_name': '机械硬盘信息',
                'verbose_name_plural': '机械硬盘信息',
            },
        ),
    ]
