# Generated by Django 3.2.10 on 2022-04-26 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hdds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hdd',
            name='disk_size',
            field=models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='盘体尺寸'),
        ),
        migrations.AlterField(
            model_name='hdd',
            name='disk_type',
            field=models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='机械硬盘类型'),
        ),
        migrations.AlterField(
            model_name='hdd',
            name='interface_type',
            field=models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='接口类型'),
        ),
        migrations.AlterField(
            model_name='hdd',
            name='manufacturer',
            field=models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='制造厂方'),
        ),
        migrations.AlterField(
            model_name='hdd',
            name='name',
            field=models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='机械硬盘名称'),
        ),
        migrations.AlterField(
            model_name='hdd',
            name='transmission_standard',
            field=models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='传输标准'),
        ),
    ]
