# Generated by Django 3.2.10 on 2022-04-25 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mainboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=128, verbose_name='主板名称')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='主板价格')),
                ('manufacturer', models.CharField(default='', max_length=128, verbose_name='制造厂方')),
                ('chipset', models.CharField(default='', max_length=64, verbose_name='芯片组')),
                ('CPU_slot', models.CharField(default='', max_length=64, verbose_name='CPU插槽')),
                ('mainboard_architecture', models.CharField(default='', max_length=64, verbose_name='主板架构')),
                ('supported_memory_types', models.CharField(default='', max_length=128, verbose_name='支持内存类型')),
                ('memory_frequency', models.IntegerField(blank=True, null=True, verbose_name='内存频率')),
                ('max_memory_capacity', models.IntegerField(blank=True, null=True, verbose_name='最大支持内存容量')),
                ('onboard_sound_card', models.CharField(default='', max_length=128, verbose_name='板载声卡')),
                ('onboard_network_card', models.CharField(default='', max_length=128, verbose_name='板载网卡')),
                ('SATA_3_interface_number', models.IntegerField(blank=True, null=True, verbose_name='SATA3接口数量')),
                ('socket_interface', models.CharField(default='', max_length=128, verbose_name='插槽接口')),
                ('extension_interface', models.CharField(default='', max_length=128, verbose_name='扩展接口')),
                ('power_interface', models.CharField(default='', max_length=128, verbose_name='电源接口')),
                ('overall_dimension', models.CharField(default='', max_length=64, verbose_name='外形尺寸')),
            ],
            options={
                'verbose_name': '主板信息',
                'verbose_name_plural': '主板信息',
            },
        ),
    ]
