# Generated by Django 3.2.10 on 2022-04-26 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainboards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainboard',
            name='CPU_slot',
            field=models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='CPU插槽'),
        ),
        migrations.AlterField(
            model_name='mainboard',
            name='chipset',
            field=models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='芯片组'),
        ),
        migrations.AlterField(
            model_name='mainboard',
            name='extension_interface',
            field=models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='扩展接口'),
        ),
        migrations.AlterField(
            model_name='mainboard',
            name='mainboard_architecture',
            field=models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='主板架构'),
        ),
        migrations.AlterField(
            model_name='mainboard',
            name='manufacturer',
            field=models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='制造厂方'),
        ),
        migrations.AlterField(
            model_name='mainboard',
            name='name',
            field=models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='主板名称'),
        ),
        migrations.AlterField(
            model_name='mainboard',
            name='onboard_network_card',
            field=models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='板载网卡'),
        ),
        migrations.AlterField(
            model_name='mainboard',
            name='onboard_sound_card',
            field=models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='板载声卡'),
        ),
        migrations.AlterField(
            model_name='mainboard',
            name='overall_dimension',
            field=models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='外形尺寸'),
        ),
        migrations.AlterField(
            model_name='mainboard',
            name='power_interface',
            field=models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='电源接口'),
        ),
        migrations.AlterField(
            model_name='mainboard',
            name='socket_interface',
            field=models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='插槽接口'),
        ),
        migrations.AlterField(
            model_name='mainboard',
            name='supported_memory_types',
            field=models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='支持内存类型'),
        ),
    ]
