# Generated by Django 3.2.10 on 2022-04-25 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Power',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=128, verbose_name='电源名称')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='电源价格')),
                ('manufacturer', models.CharField(default='', max_length=128, verbose_name='制造厂方')),
                ('power_standard', models.CharField(default='', max_length=128, verbose_name='电源标准')),
                ('rated_power', models.IntegerField(blank=True, null=True, verbose_name='额定功率')),
                ('max_power', models.IntegerField(blank=True, null=True, verbose_name='最大功率')),
                ('fan_description', models.CharField(default='', max_length=128, verbose_name='风扇描述')),
                ('certification_specification', models.CharField(default='', max_length=128, verbose_name='认证规范')),
                ('mainboard_interface', models.CharField(default='', max_length=128, verbose_name='主板电源接口')),
                ('CPU_interface', models.CharField(default='', max_length=128, verbose_name='CPU供电接口')),
                ('large4pin_interface', models.IntegerField(blank=True, null=True, verbose_name='供电接口(大4pin)')),
                ('SATA_interface', models.IntegerField(blank=True, null=True, verbose_name='SATA接口')),
                ('GPU_interface_8pin', models.CharField(default='', max_length=64, verbose_name='8Pin显卡电源接口')),
                ('AC_input', models.CharField(default='', max_length=64, verbose_name='交流输入')),
                ('PFC_type', models.CharField(default='', max_length=64, verbose_name='PFC类型')),
                ('plus80_certification', models.CharField(default='', max_length=64, verbose_name='80PLUS认证')),
                ('conversion_efficiency', models.IntegerField(blank=True, null=True, verbose_name='转换效率')),
                ('power_size', models.CharField(default='', max_length=64, verbose_name='电源尺寸')),
            ],
            options={
                'verbose_name': '电源信息',
                'verbose_name_plural': '电源信息',
            },
        ),
    ]
