# Generated by Django 3.2.10 on 2022-04-26 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='power',
            name='AC_input',
            field=models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='交流输入'),
        ),
        migrations.AlterField(
            model_name='power',
            name='CPU_interface',
            field=models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='CPU供电接口'),
        ),
        migrations.AlterField(
            model_name='power',
            name='GPU_interface_8pin',
            field=models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='8Pin显卡电源接口'),
        ),
        migrations.AlterField(
            model_name='power',
            name='PFC_type',
            field=models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='PFC类型'),
        ),
        migrations.AlterField(
            model_name='power',
            name='certification_specification',
            field=models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='认证规范'),
        ),
        migrations.AlterField(
            model_name='power',
            name='fan_description',
            field=models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='风扇描述'),
        ),
        migrations.AlterField(
            model_name='power',
            name='mainboard_interface',
            field=models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='主板电源接口'),
        ),
        migrations.AlterField(
            model_name='power',
            name='manufacturer',
            field=models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='制造厂方'),
        ),
        migrations.AlterField(
            model_name='power',
            name='name',
            field=models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='电源名称'),
        ),
        migrations.AlterField(
            model_name='power',
            name='plus80_certification',
            field=models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='80PLUS认证'),
        ),
        migrations.AlterField(
            model_name='power',
            name='power_size',
            field=models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='电源尺寸'),
        ),
        migrations.AlterField(
            model_name='power',
            name='power_standard',
            field=models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='电源标准'),
        ),
    ]
